# Generated by Django 5.1.15 on 2026-09-17 02:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("portatil", "Portátil (Laptop)"),
                            ("desktop", "Computador de Escritorio (Desktop)"),
                            ("tablet", "Tablet / iPad"),
                        ],
                        default="portatil",
                        max_length=20,
                    ),
                ),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=80)),
                ("serial", models.CharField(db_index=True, max_length=80, unique=True)),
                (
                    "propiedad",
                    models.CharField(
                        choices=[
                            (
                                "institucional",
                                "Institucional (Propiedad de la Universidad)",
                            ),
                            ("personal", "Personal (Propiedad del Miembro)"),
                        ],
                        default="personal",
                        help_text="Tipo de propiedad del equipo",
                        max_length=20,
                    ),
                ),
                (
                    "token_qr",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador interno codificado en el QR",
                        unique=True,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Borrado lógico (baja de equipo)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "persona",
                    models.ForeignKey(
                        help_text="Dueño del equipo (comunidad académica)",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="equipos",
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "db_table": "equipo",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["serial"], name="equipo_serial_8c1f0a_idx"),
                    models.Index(fields=["token_qr"], name="equipo_token_q_2d336e_idx"),
                    models.Index(fields=["persona"], name="equipo_persona_d79290_idx"),
                ],
            },
        ),
    ]
