# Generated by Django 5.1.15 on 2026-09-19 22:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipos", "0002_equipo_dependencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipo",
            name="propiedad",
            field=models.CharField(
                choices=[
                    ("institucional", "De dependencia (institucional)"),
                    ("personal", "Personal (Propiedad del Miembro)"),
                ],
                default="personal",
                help_text="Tipo de propiedad del equipo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="token_qr",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Identificador interno permanente del equipo (no se exhibe crudo en el QR)",
                unique=True,
            ),
        ),
    ]
