# Generated by Django 5.1.15 on 2026-09-20 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipos", "0003_alter_equipo_propiedad_alter_equipo_token_qr"),
        ("organizacion", "0004_responsable_y_unidad_equipo"),
        ("personas", "0004_alter_persona_programa_alter_tipovinculo_codigo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="asignado_por_usuario",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la asignación institucional",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipos_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipo",
            name="fecha_asignacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipo",
            name="unidad_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="ID de Facultad, Programa o Área según unidad_tipo",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="equipo",
            name="unidad_tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("facultad", "Facultad"),
                    ("programa", "Programa"),
                    ("area", "Área / Dependencia"),
                ],
                help_text="Solo para equipos institucionales",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="dependencia",
            field=models.ForeignKey(
                blank=True,
                help_text="Área si unidad_tipo=area (compatibilidad); null para facultad/programa",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="equipos",
                to="organizacion.area",
            ),
        ),
        migrations.AddIndex(
            model_name="equipo",
            index=models.Index(
                fields=["unidad_tipo", "unidad_id"], name="equipo_unidad__847342_idx"
            ),
        ),
    ]
