# Generated by Django 5.1.15 on 2026-09-20 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipos", "0007_inventario_unidad_en_equipo"),
        ("organizacion", "0004_responsable_y_unidad_equipo"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="equipo",
            new_name="equipo_unidad__847342_idx",
            old_name="equipo_unidad_prop_idx",
        ),
        migrations.RenameIndex(
            model_name="equipo",
            new_name="equipo_estado__c83d9b_idx",
            old_name="equipo_estado_inv_idx",
        ),
        migrations.AlterField(
            model_name="equipo",
            name="dependencia",
            field=models.ForeignKey(
                blank=True,
                help_text="Área si unidad_tipo=area (compatibilidad inventario)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="equipos",
                to="organizacion.area",
            ),
        ),
    ]
