# Generated by Django 5.1.15 on 2026-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_inventario_institucional_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rol",
            name="nombre",
            field=models.CharField(
                help_text="Nombre del rol (ej. miembro_comunidad, vigilante, admin_sistema)",
                max_length=50,
                unique=True,
            ),
        ),
    ]
