# Generated by Django 5.1.15 on 2026-09-17 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogCambioRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_que_modifico",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_cambio_rol",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de cambio de rol/permiso",
                "verbose_name_plural": "Logs de cambios de rol/permiso",
                "db_table": "log_cambio_rol",
                "ordering": ["-created_at"],
            },
        ),
    ]
