# Generated by Django 5.1.15 on 2026-09-17 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Decanatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código corto institucional (ej. FAC-ING)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, help_text="Borrado lógico"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Decanatura / Facultad",
                "verbose_name_plural": "Decanaturas / Facultades",
                "db_table": "decanatura",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código corto institucional (ej. UBATE, FUSA, GIR)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("ciudad", models.CharField(max_length=100)),
                (
                    "activo",
                    models.BooleanField(default=True, help_text="Borrado lógico"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
                "db_table": "sede",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Programa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código SNIES o institucional",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[("pregrado", "Pregrado"), ("posgrado", "Posgrado")],
                        default="pregrado",
                        max_length=20,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, help_text="Borrado lógico"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decanatura",
                    models.ForeignKey(
                        help_text="Decanatura a la que pertenece el programa",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="programas",
                        to="organizacion.decanatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa Académico",
                "verbose_name_plural": "Programas Académicos",
                "db_table": "programa",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="decanatura",
            name="sede",
            field=models.ForeignKey(
                help_text="Sede a la que pertenece la decanatura/facultad",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="decanaturas",
                to="organizacion.sede",
            ),
        ),
    ]
