# Generated by Django 5.1.15 on 2026-09-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizacion", "0002_reestructurar_organizacion"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="programa",
            new_name="programa_sede_id_b1dd9e_idx",
            old_name="programa_sede_fac_idx",
        ),
    ]
