# Generated by Django 5.1.15 on 2026-09-20 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizacion",
            "0003_rename_programa_sede_fac_idx_programa_sede_id_b1dd9e_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponsableDependencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unidad_tipo",
                    models.CharField(
                        choices=[
                            ("facultad", "Facultad"),
                            ("programa", "Programa"),
                            ("area", "Área / Dependencia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "unidad_id",
                    models.PositiveBigIntegerField(
                        help_text="ID de la Facultad, Programa o Área según unidad_tipo"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, help_text="Borrado lógico"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsabilidades_dependencia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsable de dependencia",
                "verbose_name_plural": "Responsables de dependencia",
                "db_table": "responsable_dependencia",
                "ordering": ["unidad_tipo", "unidad_id"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "activo"],
                        name="responsable_usuario_c0282a_idx",
                    ),
                    models.Index(
                        fields=["unidad_tipo", "unidad_id"],
                        name="responsable_unidad__b25df4_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "unidad_tipo", "unidad_id"),
                        name="uniq_responsable_usuario_unidad",
                    )
                ],
            },
        ),
    ]
