# Generated by Django 5.1.15 on 2026-09-22 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizacion", "0005_alcance_usuario"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="alcanceusuario",
            new_name="alcance_usu_usuario_331d8c_idx",
            old_name="alcance_usuario_usuario_activo_idx",
        ),
        migrations.RenameIndex(
            model_name="alcanceusuario",
            new_name="alcance_usu_nivel_54dee8_idx",
            old_name="alcance_usuario_nivel_obj_idx",
        ),
    ]
