# -*- coding: utf-8 -*-
"""Catalogos institucionales UCundinamarca para seed_data (fuente: Universiad_de_Cundinamarca_Info.xlsx)."""

SEDES = [
    {'codigo': 'CHIA', 'nombre': 'Extensión Chía', 'ciudad': 'Chía'},
    {'codigo': 'FACA', 'nombre': 'Extensión Facatativá', 'ciudad': 'Facatativá'},
    {'codigo': 'FUSA', 'nombre': 'Sede Fusagasugá', 'ciudad': 'Fusagasugá'},
    {'codigo': 'GIR', 'nombre': 'Seccional Girardot', 'ciudad': 'Girardot'},
    {'codigo': 'SOACHA', 'nombre': 'Extensión Soacha', 'ciudad': 'Soacha'},
    {'codigo': 'UBATE', 'nombre': 'Seccional Ubaté', 'ciudad': 'Ubaté'},
    {'codigo': 'ZIPA', 'nombre': 'Extensión Zipaquirá', 'ciudad': 'Zipaquirá'},
]

FACULTADES = [
    {'codigo': 'FAC-ADM', 'nombre': 'Ciencias Administrativas, Económicas y Contables'},
    {'codigo': 'FAC-AGRO', 'nombre': 'Ciencias Agropecuarias'},
    {'codigo': 'FAC-DEP', 'nombre': 'Ciencias del Deporte y la Educación Física'},
    {'codigo': 'FAC-EDU', 'nombre': 'Educación'},
    {'codigo': 'FAC-ING', 'nombre': 'Ingeniería'},
    {'codigo': 'FAC-SALUD', 'nombre': 'Ciencias de la Salud'},
    {'codigo': 'FAC-SOC', 'nombre': 'Ciencias Sociales, Humanidades y Ciencias Políticas'},
]

PROGRAMAS = [
    {'codigo': 'ADM-FUSA', 'nombre': 'Administración de Empresas', 'sede': 'FUSA', 'facultad': 'FAC-ADM', 'nivel': 'pregrado'},
    {'codigo': 'CONT-FUSA', 'nombre': 'Contaduría Pública', 'sede': 'FUSA', 'facultad': 'FAC-ADM', 'nivel': 'pregrado'},
    {'codigo': 'IAGRO-FUSA', 'nombre': 'Ingeniería Agronómica', 'sede': 'FUSA', 'facultad': 'FAC-AGRO', 'nivel': 'pregrado'},
    {'codigo': 'ZOO-FUSA', 'nombre': 'Zootecnia', 'sede': 'FUSA', 'facultad': 'FAC-AGRO', 'nivel': 'pregrado'},
    {'codigo': 'ENF-FUSA', 'nombre': 'Enfermería', 'sede': 'FUSA', 'facultad': 'FAC-SALUD', 'nivel': 'pregrado'},
    {'codigo': 'DEP-FUSA', 'nombre': 'Profesional en Ciencias del Deporte', 'sede': 'FUSA', 'facultad': 'FAC-DEP', 'nivel': 'pregrado'},
    {'codigo': 'PSI-FUSA', 'nombre': 'Psicología', 'sede': 'FUSA', 'facultad': 'FAC-SOC', 'nivel': 'pregrado'},
    {'codigo': 'MUS-FUSA', 'nombre': 'Música', 'sede': 'FUSA', 'facultad': 'FAC-SOC', 'nivel': 'pregrado'},
    {'codigo': 'LICSOC-FUSA', 'nombre': 'Licenciatura en Ciencias Sociales', 'sede': 'FUSA', 'facultad': 'FAC-EDU', 'nivel': 'pregrado'},
    {'codigo': 'LICEDF-FUSA', 'nombre': 'Licenciatura en Educación Física, Recreación y Deportes', 'sede': 'FUSA', 'facultad': 'FAC-EDU', 'nivel': 'pregrado'},
    {'codigo': 'ISC-FUSA', 'nombre': 'Ingeniería de Sistemas y Computación', 'sede': 'FUSA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'ISOFT-FUSA', 'nombre': 'Ingeniería de Software', 'sede': 'FUSA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'IELEC-FUSA', 'nombre': 'Ingeniería Electrónica', 'sede': 'FUSA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'IIND-FUSA', 'nombre': 'Ingeniería Industrial', 'sede': 'FUSA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'IMEC-FUSA', 'nombre': 'Ingeniería Mecatrónica', 'sede': 'FUSA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'ITOP-FUSA', 'nombre': 'Ingeniería Topográfica y Geomática', 'sede': 'FUSA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'ENF-GIR', 'nombre': 'Enfermería', 'sede': 'GIR', 'facultad': 'FAC-SALUD', 'nivel': 'pregrado'},
    {'codigo': 'ADM-GIR', 'nombre': 'Administración de Empresas', 'sede': 'GIR', 'facultad': 'FAC-ADM', 'nivel': 'pregrado'},
    {'codigo': 'IS-GIR', 'nombre': 'Ingeniería de Sistemas', 'sede': 'GIR', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'IIND-GIR', 'nombre': 'Ingeniería Industrial', 'sede': 'GIR', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'IAMB-GIR', 'nombre': 'Ingeniería Ambiental', 'sede': 'GIR', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'ADM-UBATE', 'nombre': 'Administración de Empresas', 'sede': 'UBATE', 'facultad': 'FAC-ADM', 'nivel': 'pregrado'},
    {'codigo': 'CONT-UBATE', 'nombre': 'Contaduría Pública', 'sede': 'UBATE', 'facultad': 'FAC-ADM', 'nivel': 'pregrado'},
    {'codigo': 'ZOO-UBATE', 'nombre': 'Zootecnia', 'sede': 'UBATE', 'facultad': 'FAC-AGRO', 'nivel': 'pregrado'},
    {'codigo': 'MVZ-UBATE', 'nombre': 'Medicina Veterinaria y Zootecnia', 'sede': 'UBATE', 'facultad': 'FAC-AGRO', 'nivel': 'pregrado'},
    {'codigo': 'ISC-UBATE', 'nombre': 'Ingeniería de Sistemas y Computación', 'sede': 'UBATE', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'ADM-CHIA', 'nombre': 'Administración de Empresas', 'sede': 'CHIA', 'facultad': 'FAC-ADM', 'nivel': 'pregrado'},
    {'codigo': 'CONT-CHIA', 'nombre': 'Contaduría Pública', 'sede': 'CHIA', 'facultad': 'FAC-ADM', 'nivel': 'pregrado'},
    {'codigo': 'ISC-CHIA', 'nombre': 'Ingeniería de Sistemas y Computación', 'sede': 'CHIA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'IIND-CHIA', 'nombre': 'Ingeniería Industrial', 'sede': 'CHIA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'IMEC-CHIA', 'nombre': 'Ingeniería Mecatrónica', 'sede': 'CHIA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'ADM-FACA', 'nombre': 'Administración de Empresas', 'sede': 'FACA', 'facultad': 'FAC-ADM', 'nivel': 'pregrado'},
    {'codigo': 'CONT-FACA', 'nombre': 'Contaduría Pública', 'sede': 'FACA', 'facultad': 'FAC-ADM', 'nivel': 'pregrado'},
    {'codigo': 'PSI-FACA', 'nombre': 'Psicología', 'sede': 'FACA', 'facultad': 'FAC-SOC', 'nivel': 'pregrado'},
    {'codigo': 'IS-FACA', 'nombre': 'Ingeniería de Sistemas', 'sede': 'FACA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'IAMB-FACA', 'nombre': 'Ingeniería Ambiental', 'sede': 'FACA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'ADM-SOACHA', 'nombre': 'Administración de Empresas', 'sede': 'SOACHA', 'facultad': 'FAC-ADM', 'nivel': 'pregrado'},
    {'codigo': 'CONT-SOACHA', 'nombre': 'Contaduría Pública', 'sede': 'SOACHA', 'facultad': 'FAC-ADM', 'nivel': 'pregrado'},
    {'codigo': 'DEP-SOACHA', 'nombre': 'Profesional en Ciencias del Deporte', 'sede': 'SOACHA', 'facultad': 'FAC-DEP', 'nivel': 'pregrado'},
    {'codigo': 'IIND-SOACHA', 'nombre': 'Ingeniería Industrial', 'sede': 'SOACHA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'ISOFT-SOACHA', 'nombre': 'Ingeniería de Software', 'sede': 'SOACHA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'ITOP-SOACHA', 'nombre': 'Ingeniería Topográfica y Geomática', 'sede': 'SOACHA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'IEER-SOACHA', 'nombre': 'Ingeniería en Electrónica y Energías Renovables', 'sede': 'SOACHA', 'facultad': 'FAC-ING', 'nivel': 'pregrado'},
    {'codigo': 'DEPED-ZIPA', 'nombre': 'Profesional en Ciencias del Deporte y la Educación Física', 'sede': 'ZIPA', 'facultad': 'FAC-DEP', 'nivel': 'pregrado'},
    {'codigo': 'MUS-ZIPA', 'nombre': 'Música', 'sede': 'ZIPA', 'facultad': 'FAC-SOC', 'nivel': 'pregrado'},
]

AREAS = [
    {'codigo': 'ADMIS', 'nombre': 'Admisiones y Registro'},
    {'codigo': 'BIEN', 'nombre': 'Bienestar Universitario'},
    {'codigo': 'CGCA', 'nombre': 'CGCA (Centro de Gestión del Conocimiento y el Aprendizaje - Biblioteca)'},
    {'codigo': 'CTEI', 'nombre': 'CTeI (Ciencia, Tecnología e Innovación)'},
    {'codigo': 'DIRADM', 'nombre': 'Dirección Administrativa'},
    {'codigo': 'INTL', 'nombre': 'Dialogando con el Mundo (Internacionalización)'},
    {'codigo': 'ISU', 'nombre': 'ISU (Interacción Social Universitaria)'},
    {'codigo': 'TESOR', 'nombre': 'Tesorería / Gestión Financiera'},
]
