# Generated by Django 5.1.15 on 2026-09-17 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_escaneado",
                    models.CharField(
                        blank=True,
                        help_text="Cadena exacta recibida por el lector de código de barras/QR",
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("ok", "Coincide / Autorizado (OK)"),
                            ("alerta", "Alerta de Seguridad"),
                            ("no_encontrado", "No Encontrado en Base de Datos"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Equipo escaneado (null si no existe en BD)",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="movimientos",
                        to="equipos.equipo",
                    ),
                ),
                (
                    "usuario_control",
                    models.ForeignKey(
                        help_text="Celador o personal de control que realizó el escaneo",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="movimientos_controlados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Control",
                "verbose_name_plural": "Movimientos de Control",
                "db_table": "movimiento",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="movimiento_timesta_fd2ef4_idx"
                    ),
                    models.Index(
                        fields=["equipo"], name="movimiento_equipo__d21473_idx"
                    ),
                    models.Index(
                        fields=["resultado"], name="movimiento_resulta_d98a86_idx"
                    ),
                ],
            },
        ),
    ]
