# Generated by Django 5.1.15 on 2026-09-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_acceso", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimiento",
            name="motivo_alerta",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equipo_inactivo", "Equipo inactivo"),
                    ("persona_inactiva", "Persona inactiva"),
                    ("no_coincide", "No coincide"),
                    ("asignacion_vencida", "Asignación institucional vencida"),
                    ("asignacion_no_vigente", "Asignación institucional no vigente"),
                ],
                db_index=True,
                help_text="Motivo tipificado cuando resultado=alerta",
                max_length=40,
                null=True,
            ),
        ),
    ]
