# Generated by Django 5.1.15 on 2026-09-20 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_acceso", "0003_sin_asignacion_activa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movimiento",
            name="otra_sede",
            field=models.BooleanField(
                default=False,
                help_text="True si la sede de la persona no coincide con la del vigilante (doc 16)",
            ),
        ),
        migrations.AlterField(
            model_name="movimiento",
            name="motivo_alerta",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equipo_inactivo", "Equipo inactivo"),
                    ("persona_inactiva", "Persona inactiva"),
                    ("no_coincide", "No coincide"),
                    ("asignacion_vencida", "Asignación institucional vencida"),
                    ("asignacion_no_vigente", "Asignación institucional no vigente"),
                    (
                        "sin_asignacion_activa",
                        "Sin asignación activa (disponible en inventario)",
                    ),
                    ("visita_vencida", "Visita de personal externo vencida"),
                    ("sin_visita_activa", "Sin visita activa de personal externo"),
                ],
                db_index=True,
                help_text="Motivo tipificado cuando resultado=alerta",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimiento",
            name="usuario_control",
            field=models.ForeignKey(
                help_text="Vigilante o personal de control que realizó el escaneo",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="movimientos_controlados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
