# Generated by Django 5.1.15 on 2026-09-17 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("TI", "Tarjeta de Identidad"),
                            ("PAS", "Pasaporte"),
                        ],
                        default="CC",
                        max_length=5,
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("nombres", models.CharField(max_length=150)),
                ("apellidos", models.CharField(max_length=150)),
                (
                    "tipo_vinculo",
                    models.CharField(
                        choices=[
                            ("docente", "Docente"),
                            ("administrativo", "Administrativo"),
                            ("gestor_conocimiento", "Gestor de Conocimiento"),
                            ("creador_oportunidades", "Creador de Oportunidades"),
                            ("graduado", "Graduado"),
                        ],
                        help_text="Rol funcional dentro de la comunidad académica (Docente, Administrativo, Gestor...)",
                        max_length=30,
                    ),
                ),
                (
                    "foto_url",
                    models.CharField(
                        blank=True,
                        help_text="URL o ruta de la foto institucional",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="personas/"),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, help_text="Borrado lógico"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "programa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Programa asociado (aplica a docentes/graduados)",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="personas",
                        to="organizacion.programa",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        help_text="Sede a la que está vinculado",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="personas",
                        to="organizacion.sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
                "db_table": "persona",
                "ordering": ["apellidos", "nombres"],
            },
        ),
    ]
