# Generated by Django on 2026-09-17 for Document 06

import django.db.models.deletion
from django.db import migrations, models


def populate_tipos_vinculo(apps, schema_editor):
    TipoVinculo = apps.get_model("personas", "TipoVinculo")
    Rol = apps.get_model("accounts", "Rol")

    rol_miembro = Rol.objects.filter(nombre="miembro_comunidad").first()

    catalog = [
        {
            "codigo": "docente",
            "nombre": "Docente",
            "permite_autoregistro": False,
            "dominio_correo_requerido": None,
            "rol_asignado": rol_miembro,
        },
        {
            "codigo": "administrativo",
            "nombre": "Personal Administrativo",
            "permite_autoregistro": True,
            "dominio_correo_requerido": "@ucundinamarca.edu.co",
            "rol_asignado": rol_miembro,
        },
        {
            "codigo": "gestor_conocimiento",
            "nombre": "Gestor del Conocimiento",
            "permite_autoregistro": True,
            "dominio_correo_requerido": "@ucundinamarca.edu.co",
            "rol_asignado": rol_miembro,
        },
        {
            "codigo": "creador_oportunidades",
            "nombre": "Creador de Oportunidades",
            "permite_autoregistro": True,
            "dominio_correo_requerido": "@ucundinamarca.edu.co",
            "rol_asignado": rol_miembro,
        },
        {
            "codigo": "graduado",
            "nombre": "Graduado",
            "permite_autoregistro": True,
            "dominio_correo_requerido": "@ucundinamarca.edu.co",
            "rol_asignado": rol_miembro,
        },
        {
            "codigo": "estudiante",
            "nombre": "Estudiante",
            "permite_autoregistro": True,
            "dominio_correo_requerido": "@ucundinamarca.edu.co",
            "rol_asignado": rol_miembro,
        },
    ]

    for item in catalog:
        TipoVinculo.objects.get_or_create(
            codigo=item["codigo"],
            defaults=item,
        )


def migrate_persona_vinculos(apps, schema_editor):
    Persona = apps.get_model("personas", "Persona")
    TipoVinculo = apps.get_model("personas", "TipoVinculo")

    for persona in Persona.objects.all():
        old_val = getattr(persona, "tipo_vinculo", None)
        if old_val:
            tv = TipoVinculo.objects.filter(codigo=old_val).first()
            if not tv:
                tv = TipoVinculo.objects.filter(codigo="docente").first()
            persona.tipo_vinculo_new = tv
            persona.save(update_fields=["tipo_vinculo_new"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoVinculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único (ej. docente, administrativo, gestor_conocimiento, graduado, estudiante)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                (
                    "permite_autoregistro",
                    models.BooleanField(
                        default=False,
                        help_text="Si un usuario externo puede crear su cuenta eligiendo este tipo",
                    ),
                ),
                (
                    "dominio_correo_requerido",
                    models.CharField(
                        blank=True,
                        help_text="ej. @ucundinamarca.edu.co; si es nulo, no se exige dominio específico",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, help_text="Borrado lógico"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rol_asignado",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rol que se asigna automáticamente al autorregistrarse con este tipo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tipos_vinculo",
                        to="accounts.rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Vínculo",
                "verbose_name_plural": "Tipos de Vínculo",
                "db_table": "tipo_vinculo",
                "ordering": ["nombre"],
            },
        ),
        migrations.RunPython(populate_tipos_vinculo, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="persona",
            name="tipo_vinculo_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="personas",
                to="personas.tipovinculo",
            ),
        ),
        migrations.RunPython(migrate_persona_vinculos, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="persona",
            name="tipo_vinculo",
        ),
        migrations.RenameField(
            model_name="persona",
            old_name="tipo_vinculo_new",
            new_name="tipo_vinculo",
        ),
        migrations.AlterField(
            model_name="persona",
            name="tipo_vinculo",
            field=models.ForeignKey(
                help_text="Rol funcional dentro de la comunidad académica (Docente, Administrativo, Gestor...)",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="personas",
                to="personas.tipovinculo",
            ),
        ),
    ]
