# Generated by Django 5.1.15 on 2026-09-19 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizacion",
            "0003_rename_programa_sede_fac_idx_programa_sede_id_b1dd9e_idx",
        ),
        ("personas", "0003_persona_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="programa",
            field=models.ForeignKey(
                blank=True,
                help_text="Programa asociado (aplica a perfiles académicos)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="personas",
                to="organizacion.programa",
            ),
        ),
        migrations.AlterField(
            model_name="tipovinculo",
            name="codigo",
            field=models.CharField(
                help_text="Código único (ej. gestor_administrativo, creador_oportunidades, gestor_conocimiento, egresado)",
                max_length=30,
                unique=True,
            ),
        ),
    ]
