# Generated by Django 5.1.15 on 2026-09-20 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizacion", "0004_responsable_y_unidad_equipo"),
        ("personas", "0004_alter_persona_programa_alter_tipovinculo_codigo"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitaExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unidad_tipo",
                    models.CharField(
                        choices=[
                            ("facultad", "Facultad"),
                            ("programa", "Programa"),
                            ("area", "Área / Dependencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unidad_id", models.PositiveBigIntegerField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="activa",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "persona",
                    models.ForeignKey(
                        help_text="Persona con tipo_vinculo=personal_externo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitas_externo",
                        to="personas.persona",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="visitas_externo",
                        to="organizacion.sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visita de personal externo",
                "verbose_name_plural": "Visitas de personal externo",
                "db_table": "visita_externo",
                "ordering": ["-fecha_inicio", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["persona", "estado"],
                        name="visita_exte_persona_7213cf_idx",
                    ),
                    models.Index(
                        fields=["fecha_fin", "estado"],
                        name="visita_exte_fecha_f_e85644_idx",
                    ),
                ],
            },
        ),
    ]
