# Generated by Django 5.1.15 on 2026-09-22 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResendWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("svix_id", models.CharField(max_length=100, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField(default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "resend_webhook_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_type", models.CharField(max_length=50)),
                ("recipient", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En cola"),
                            ("sent", "Enviado"),
                            ("failed", "Fallido"),
                            ("delivered", "Entregado"),
                            ("bounced", "Rebotado"),
                            ("complained", "Queja"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("resend_id", models.CharField(blank=True, default="", max_length=100)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "email_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resend_id"], name="email_log_resend__6db987_idx"
                    ),
                    models.Index(
                        fields=["recipient", "created_at"],
                        name="email_log_recipie_bf8a58_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("email_confirmation", "Confirmación de correo"),
                            ("password_reset", "Restablecer contraseña"),
                        ],
                        max_length=30,
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=64)),
                ("email_sent_to", models.EmailField(max_length=254)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_token",
                "indexes": [
                    models.Index(
                        fields=["purpose", "token_hash"],
                        name="email_token_purpose_18e8bf_idx",
                    )
                ],
            },
        ),
    ]
