# Generated by Django — create auditoria_cambio

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditoriaCambio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entidad", models.CharField(db_index=True, max_length=50)),
                ("entidad_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("crear", "Crear"),
                            ("editar", "Editar"),
                            ("inactivar", "Inactivar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detalle", models.JSONField(blank=True, default=dict)),
                ("ip_origen", models.CharField(blank=True, default="", max_length=45)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría de cambio",
                "verbose_name_plural": "Auditorías de cambio",
                "db_table": "auditoria_cambio",
                "ordering": ["-timestamp"],
            },
        ),
    ]
